# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
