# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 23:34
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_job_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='internal_job',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='open_job',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='validity',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 22, 23, 34, 36, 512801, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='workload',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(45)]),
            preserve_default=False,
        ),
    ]
